#
# Pints functional testing command line utility.
#
# This file is part of Pints Functional Testing.
#  Copyright (c) 2017-2019, University of Oxford.
#  For licensing information, see the LICENSE file distributed with the Pints
#  functional testing software package.
#

trigger: none

pr: none

schedules:
- cron: "0 * * * *"
  displayName: Hourly next functional test
  branches:
    include:
    - master
  always: true

jobs:
